team_colors = {
    "Diamondbacks": "#A71930",
    "Braves": "#CE1141",
    "Orioles": "#DF4601",
    "Red Sox": "#BD3039",
    "Cubs": "#0E3386",
    "White Sox": "#27251F",
    "Reds": "#C6011F",
    "Cleveland": "0C2340",
    "Rockies": "#33006F",
    "Tigers": "#0C2340",
    "Astros": "#002D62",
    "Royals": "#004687",
    "Angels": "#003263",
    "Dodgers": "#005A9C",
    "Marlins": "#00A3E0",
    "Brewers": "#FFC52F",
    "Twins": "#002B5C",
    "Mets": "#002D72",
    "Yankees": "#003087",
    "Athletics": "#003831",
    "Phillies": "#E81828",
    "Pirates": "#27251F",
    "Cardinals": "#C41E3A",
    "Padres": "#2F241D",
    "Giants": "#FD5A1E",
    "Mariners": "#0C2C56",
    "Rays": "#092C5C",
    "Rangers": "#003278",
    "Blue Jays": "#134A8E",
    "Nationals": "#AB0003"
}

stat_descriptions = {
    "W": "wins",
    "L": "losses",
    "Wpct": "win percentage",
    "GB": "games back in the division",
    "WCGB": "games back in the wildcard",
    "endData.ExpW": "expected wins",
    "endData.ExpL": "expected losses",
    "endData.rosW": "rest of season win percentage",
    "endData.divTitle": "odds of winning the division",
    "endData.wcTitle": "odds of winning the wildcard",
    "endData.poffTitle": "odds of making the playoffs",
    "endData.wcWin": "odds of advancing to the division series",
    "endData.dsWin": "odds of advancing to the league championship series",
    "endData.csWin": "odds of advancing to the world series",
    "endData.wsWin": "odds of winning the world series",
    "endData.sos": "strength of schedule"
}